import {playground} from './playground';
import {meeting} from './meeting';
import {lunch} from './lunch';
import {vias,viasRush} from './vias';
import {qfn} from './qfn';
import {archive} from './archive';
import {waterworks} from './waterworks';
import {observatory} from './observatory';
import {clockwork} from './clockwork';
export const levels=[playground,meeting,lunch,vias,viasRush,qfn,archive,waterworks,observatory,clockwork];
